project:
  type: website
  output-dir: docs

website:
  title: "inat-daily-activity-analysis"
  navbar:
    left:
      - href: index.qmd
        text: About
      - data_prep.qmd
      - descriptive.qmd
      - bias_adjust_example.qmd
      - model_selection.qmd
      - publication_figures.qmd
      - bimodality.qmd
      - observer_timings.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual