project:
  type: website
  output-dir: docs

website:
  title: "inat-daily-activity-analysis"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - data_prep.qmd
      - descriptive.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual